train_cfg:
  root: "/root/autodl-tmp/Datasets/WildDeepfake"
  split: "train"
  classes: ["real", "fake"]
  # ###################################
  balance: True
  # ##############################
  num_image_train:
#  log_steps: 200
#  val_steps: 200
  log_steps: 2500
  val_steps: 2500
  num_steps: 40000
  transforms:
    - name: "Resize"
      params:
        height: 224
        width: 224
    - name: "HorizontalFlip"
      params:
        p: 0.5
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
test_cfg:
  root: "/root/autodl-tmp/Datasets/WildDeepfake"
  split: "test"
  balance: False
  # ##############################
  num_image_test:
  transforms:
    - name: "Resize"
      params:
        height: 224
        width: 224
    - name: "Normalize"
      params:
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]